name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - jupyterlab==3.0.12
      - seaborn==0.11.1
      - pandas==1.4.2
      - pandas-profiling==3.0.0
      - pyarrow==2.0
      - protobuf==3.20.*
      #- Jinja2==3.1.1
      - jinja2<3.1.0
      - MarkupSafe==2.0.1
      - numpy==1.22.3
      - ipywidgets==7.7.2